### ISSUE TITLE
[coase] execution testing failing

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-advanced#123]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/8263752/81515109-d7d8fc80-9375-11ea-9d5e-a2dec1f8b226.png">

**Comment by najuzilu** [comment]
I get the following error when executing the lecture:
<img width="1017" alt="Screen Shot 2020-05-11 at 11 04 06 AM" src="https://user-images.githubusercontent.com/33075058/81515385-24710780-9377-11ea-9c6d-b6b01f370ada.png">

**Comment by najuzilu** [comment]
This issue was already addressed [here](https://github.com/scipy/scipy/pull/11208) but I don't see the fix reflected in the released versions.

According to this [PR](https://github.com/jonathf/chaospy/issues/198) "the solution won't be present before scipy 1.5.0."

**Comment by Harveyt47** [comment]
This is mostly occurring in `fminbound`. When the two bound are too close together this error occurs. 

See this [issue](https://github.com/QuantEcon/lecture-source-py/issues/937)

**Comment by Harveyt47** [comment]
changing `self.grid` in the ` ProductionChain`  `class` [here](https://python-advanced.quantecon.org/coase.html#Implementation) to  `self.grid = np.linspace(1e-04, 1, n)` should fix
