### ISSUE TITLE
[amss] Broken from change to opt_tax_recur

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-advanced#206]
@shizejin @QBatista it looks like there were some files updated by `opt_tax_recur` that have caused `amss` execution  to fail.

Would you be able to put a PR in for `amss` to fix the missing imports?

http://preview.python-advanced.quantecon.org.s3-website-ap-southeast-2.amazonaws.com/amss.html

**Comment by mmcky** [comment]
**Note:** this isn't on the live site (as yet) it is in the `preview` stage.

**Comment by QBatista** [comment]
@mmcky I'll take care of this when I update the AMSS lecture -- it shouldn't just be a matter of missing imports.

**Comment by mmcky** [comment]
OK great - thanks @QBatista. 

The changes to `opt_tax_recur` are sitting on our `preview` channel for the `rst` repo so I won't make that live until the `amss` lectures have been adjusted.
