### ISSUE TITLE
Files not specified in index

### ISSUE THREAD

**Issue by najuzilu** [QuantEcon/lecture-python-advanced#3]
The following three files are located in this repo but do not appear in any of the `index` files:
* `orth_proj.rst` - should be under a new index file `index_tools_and_techniques.rst`?
* `estspec.rst` - should be under `index_time_series_models.rst`
* `arma.rst` - should be under `index_time_series_models.rst`

@mmcky could you confirm that the above is correct? I'll make a PR with the necessary changes once you've confirmed.

**Comment by mmcky** [comment]
thanks @najuzilu could you cross check which `index` they should belong to in `lecture-source-py`.

**Comment by mmcky** [comment]
also are those three lectures classed as `3` in the split designation?

**Comment by najuzilu** [comment]
@mmcky yes they're classified as `3` in the split designation. The last two should belong to `index_time_series_models.rst` which I checked by going over `lecture-source-py`.  This would be very easy to fix.

However, it looks like `orth_proj.rts` is under `index_tools_and_techniques_grad.rst` which does not exists in this repo.

**Comment by mmcky** [comment]
I see. Thanks @najuzilu. 

@najuzilu could you add in a `index_tools_and_techniques.rst` with that lecture as the only listed member. Then @jstac can review the prototype later this week. We have gotten rid of all `undergrad` and `grad` index items.

**Comment by mmcky** [comment]
@najuzilu can this now be closed?
