### ISSUE TITLE
[wald_friedman] Fix context for reference to external document

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-advanced#35]
```
/wald_friedman.rst:140: WARNING: unknown document: exchangeable
/wald_friedman.rst:1011: WARNING: unknown document: exchangeable
```

**Comment by najuzilu** [comment]
@mmcky how should we go about converting if the lecture is located in a new repo? Should we use absolute paths or hrefs? Here's an example:
````
:doc:`Exchangeability and Bayesian Updating<exchangeable>`
````

The absolute path would depend a lot on how each repo is build, right?

**Comment by mmcky** [comment]
thanks @najuzilu it takes some care and iteration. I will add a style guide for this kind of update in the README.md but essentially we will update the language to point to the other lecture series (rather than specific lectures which are fragile links). Let's pick one to work on as a group to get this editing style right. 

cc: @jstac @najuzilu

**Comment by mmcky** [comment]
So this will require some updates to language surrounding the link. Project links will be:

1. python-programming.quantecon.org
1. python-intro.quantecon.org
1. python-advanced.quantecon.org
