### ISSUE TITLE
[additive_functionals] missing links to documents and labels

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-advanced#83]
/home/ubuntu/repos/lecture-python-advanced/source/rst/additive_functionals.rst:139: WARNING: unknown document: linear_models
/home/ubuntu/repos/lecture-python-advanced/source/rst/additive_functionals.rst:246: WARNING: undefined label: lss_sode (if the link has no caption the label must prece
de a section header)
/home/ubuntu/repos/lecture-python-advanced/source/rst/additive_functionals.rst:797: WARNING: unknown document: linear_models

**Comment by najuzilu** [comment]
looks like these last two issues need an additional `_`
