### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-advanced#91]
**Broken Links**

Best to grep for the links across all `rst` files

(line 236) broken https://python-intro.quantecon.org/finite_markov.html#finite_dp_stoch_mat - Anchor 'finite_dp_stoch_mat' not found
1234(line 253) broken https://python-intro.quantecon.org/finite_markov.html#finite_mc_expec - Anchor 'finite_mc_expec' not found

(line 788) broken https://python-intro.quantecon.org/optgrowth.html - 404 Client Error: Not Found for url: https://python-intro.quantecon.org/optgrowth.html
1242(line 799) broken https://python-intro.quantecon.org/optgrowth.html - 404 Client Error: Not Found for url: https://python-intro.quantecon.org/optgrowth.html

(line 1120) broken https://lectures.quantecon.org/py/optgrowth.html#Exercise-1 - Anchor 'Exercise-1' not found

**Comment by najuzilu** [comment]
@mmcky: It looks like anchors can't be referenced. 

> (line 236) broken https://python-intro.quantecon.org/finite_markov.html#finite_dp_stoch_mat - Anchor 'finite_dp_stoch_mat' not found
> 1234(line 253) broken https://python-intro.quantecon.org/finite_markov.html#finite_mc_expec - Anchor 'finite_mc_expec' not found

This `.. _finite_dp_stoch_mat:` in `rST` should be referenced at the end of the url like `#finite_dp_stoch_mat` but I'm not sure why it is not working. It's working fine in [this example](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#rst-doctest-blocks).

> (line 788) broken https://python-intro.quantecon.org/optgrowth.html - 404 Client Error: Not Found for url: https://python-intro.quantecon.org/optgrowth.html
> 1242(line 799) broken https://python-intro.quantecon.org/optgrowth.html - 404 Client Error: Not Found for url: https://python-intro.quantecon.org/optgrowth.html

Doc referencing is not working properly although `optgrowth` is in the same directory: ````:doc:`dynamic programming lecture <optgrowth>` ````.

I would appreciate any suggestions as to what we might be doing wrong.

**Comment by mmcky** [comment]
@najuzilu is the lecturing `finite_markov` moving from `intro` to `advanced`?

**Comment by jstac** [comment]
It shouldn't, FYI.

**Comment by najuzilu** [comment]
No lecture is not moving. The url to the lecture works fine ([see here](https://python-intro.quantecon.org/finite_markov.html)). I think it's what comes after `#` that's throwing this error. The target names are spelled correctly in the document and the url so I'm not sure what the issue could be.

**Comment by mmcky** [comment]
@najuzilu ah -- the title for the section has probably changed. The anchor is generated by the title of the section. 

https://python-intro.quantecon.org/finite_markov.html#Stochastic-Matrices

alternatively `.. <labelname>:` can be used to determine a point to link to in `RST`.

**Comment by mmcky** [comment]
hey @najuzilu I see. It looks like that tag hasn't made it through the `nbconvert` layer. I will look at this in more detail soon. In the meantime could you update this to use the section title (as per above).

**Comment by najuzilu** [comment]
Hi @mmcky , it looks like [lecture-python-intro](https://github.com/QuantEcon/lecture-python-intro) does not reflect our latest master which is why you are getting the following errors:

> (line 788) broken https://python-intro.quantecon.org/optgrowth.html - 404 Client Error: Not Found for url: https://python-intro.quantecon.org/optgrowth.html
> 1242(line 799) broken https://python-intro.quantecon.org/optgrowth.html - 404 Client Error: Not Found for url: https://python-intro.quantecon.org/optgrowth.html

I think these links should be fixed once the `optgrowth` lecture is available under [lecture-python-intro](https://github.com/QuantEcon/lecture-python-intro).
