### ISSUE TITLE
[titlebar] Issue with Name in drop down menu

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-advanced#92]
@DrDrij it looks like the dropdown menu may be using the site name to populate the dropdown menu. It should be "Quantitative Economics with Python". 

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/8263752/77847022-b37df200-7205-11ea-8da1-88621b72582e.png">

**Comment by DrDrij** [comment]
Fixed @mmcky 
https://github.com/QuantEcon/lecture-python-advanced.theme/pull/4
