### ISSUE TITLE
[wald friedman] broken links

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-advanced#99]
```
writing output... [ 98%] wald_friedman
(line  818) broken    http://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/Wald_Friedman.ipynb - 400 Client Error: Bad Request for url: https://nbviewer.jupyter.org/github/QuantEcon/QuantEcon.notebooks/blob/master/Wald_Friedman.ipynb
```

**Comment by najuzilu** [comment]
This file is not in the latest master. But I remember fixing this issue [here](https://github.com/QuantEcon/lecture-python-intro/pull/72/commits/9ef67bc3fa8294527b307e15ad36daf7623b4020)

**Comment by Harveyt47** [comment]
Hey guys,

I think there is a mix up. I believe that this link should be directing people to this [notebook](https://github.com/QuantEcon/QuantEcon.notebooks/blob/master/Wald_Friedman.ipynb) as the sentence the link is in is referring to the comparative static sliders generated in that notebook.

The fix @najuzilu is referring to just links back to the same lecture notebook that it is already in.

**Comment by mmcky** [comment]
it should point to the repo the lecture is contained in with `.notebooks` so if it is `lecture-python-intro` it should be `lecture-python-intro.notebooks`

**Comment by najuzilu** [comment]
@mmcky I suggest we close this issue since you should not be getting this error in this repo.
